# Generated by Codex on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScheduledRule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(default="")),
                ("service", models.TextField(default="")),
                ("action", models.TextField(default="")),
                ("enabled", models.BooleanField(default=True)),
                ("mode", models.TextField(default="times")),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True),
                ),
                ("trigger_times", models.JSONField(default=list)),
                (
                    "interval_minutes",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "last_triggered_key",
                    models.TextField(blank=True, null=True),
                ),
            ],
            options={
                "app_label": "nabplannerd",
                "ordering": ["service", "name", "id"],
            },
        ),
    ]
