# Generated by Codex on 2026-05-01

from django.db import migrations, models

import nabplannerd.models


class Migration(migrations.Migration):

    dependencies = [
        ("nabplannerd", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledrule",
            name="weekdays",
            field=models.JSONField(default=nabplannerd.models.all_weekdays),
        ),
    ]
