# Generated by Codex on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nabplannerd", "0002_scheduledrule_weekdays"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledrule",
            name="color",
            field=models.TextField(default=""),
        ),
    ]
