# Generated by Codex on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("json_url", models.TextField(default="", null=True)),
                (
                    "next_performance_date",
                    models.DateTimeField(null=True),
                ),
                ("next_performance_type", models.TextField(null=True)),
            ],
            options={
                "app_label": "nabmenudujour",
            },
        ),
    ]
